### PR TITLE
Adding "ls"

### PR DESCRIPTION
**Pull request by tebeka**
Adding "ls" command

### CODE REVIEW

**Comment by amnong** [comment]
Hi Miki,
Thanks for the patch. I'll review and merge as soon as possible.

Thanks!
Amnon

**Comment by amnong** [comment]
Hi Miki,
Thanks for your contribution :)

Amnon

**Comment by tebeka** [comment]
You're welcome, thanks for the library.

**Comment by CiaranG** [comment]
Would be nice if this patch made it into a release version.

**Comment by amnong** [comment]
Done.

**Pull request merged**
