### PR TITLE
Merging existing pull requests

### PR DESCRIPTION
**Pull request by kartoch**
I have merged non conflicting branch requests. Is there any way you can merge to the main repo and upload to pypy the new version ?

List of changes:
- fix 405 on creating existing directory
- check if remote documents exists
- create intermediate directory
- support for python3
- add an option to not verify ssl certificate
- provide file access to the file
- setting stream = True in request
- add a path option for the webdav server 
- add content type

### CODE REVIEW

**Comment by amnong** [comment]
Hello Kartoch,
Two questions, if you will:
1. Does this merge request contain all previous merge requests? You said "non conflicting merge requests" - have you left out any specific merge request? I'd like to pull your request and then remove all irrelevant requests.
2. After the adaptations to Python 3, does the code still run on Python 2.7, in all scenarios?

**Comment by amnong** [comment]
So after checking the changes I found and fixed two bugs. Due to this fact, I'm not really confident about releasing a new version to PyPI yet, but I'm going to commit the code (and my fixes) right now.

I will release a new version after I write some unit tests, I think I'm going to use PyWebDAV as the server as it seems really lite and easy to use.

**Comment by kartoch** [comment]
I've tried to merge most of the pending pull requests. The only ones not included are redundant, are changing too much the project organization or I'm not sure about them (especially the ones about `write` vs `shutil.copyfileobj`).

The problem of testing is the need for integration and unit tests. I would propose for now to tag my pull request as beta until it is well tested.

Please don't commit my last two commits.

**Comment by amnong** [comment]
Done. Closing this issue.

**Pull request closed without merging**
